# Generated by Django 4.0.2 on 2022-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/user.svg', upload_to='users/'),
        ),
    ]
