# Generated by Django 4.0.2 on 2022-03-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_redactor',
            field=models.BooleanField(default=False),
        ),
    ]
